include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DarkBootPrefs
DarkBootPrefs_FILES = DBRootListController.m
DarkBootPrefs_FRAMEWORKS = UIKit UniformTypeIdentifiers ImageIO
DarkBootPrefs_PRIVATE_FRAMEWORKS = Preferences
DarkBootPrefs_INSTALL_PATH = /Library/PreferenceBundles
DarkBootPrefs_CFLAGS = -fobjc-arc -Wall -Wextra

include $(THEOS_MAKE_PATH)/bundle.mk
