#!/bin/sh
set -e
mkdir -p "/var/mobile/Library/Application Support/Gif2Ani"
chown mobile:mobile "/var/mobile/Library/Application Support/Gif2Ani" 2>/dev/null || true
chmod 0755 "/var/mobile/Library/Application Support/Gif2Ani" 2>/dev/null || true
killall -9 Preferences 2>/dev/null || true
exit 0
